symlink:
  - title: VSCode
    dst: ~/Library/Application Support/Code/User
    src:
      - ./all/vscode/keybindings.json
      - ./all/vscode/settings.json
      - ./all/vscode/snippets

hardlink:
  - title: Karabiner
    src: ./all/karabiner/private.xml
    dst: ~/Library/Application Support/Karabiner/private.xml
