# General ------------------------------------------------------------------{{{

# Git
brew 'git'
brew 'tig'
brew 'scmpuff'

# Bunch of cool git extras
brew 'git-extras'

# Zsh
brew 'zsh'
brew 'zsh-completions'

# Defaults
brew 'python3'
brew 'nvm'
brew 'wget'
brew 'ffmpeg'

# Better unix tools
brew 'coreutils'

# Better rename using
# Example: Rename extension
# $ rename 's/(.*)/new-ext/' *.old-ext
brew 'rename'

# Move to trash cli
brew 'trash'

# NeoVim
tap 'neovim/neovim'

# To support colorprofile conversion install imagemagick with little-cms
brew 'imagemagick', args: ['with-little-cms', 'with-little-cms2']

# Tool to manage the osx dock
brew "dockutil"

# Mac appstore command line tool
brew "mas"

# Neovim
brew "neovim/neovim/neovim", args: ["HEAD"]

#}}}
# Applications -------------------------------------------------------------{{{

cask "1password"
cask "alfred"
cask "appcleaner"
cask "arduino"
cask "bartender"
cask "bettertouchtool"
cask "boom"
cask "default-folder-x"
cask "dropbox"
cask "fantastical"
cask "google-chrome"
cask "hammerspoon"
cask "hazel"
cask "iterm2-beta"
cask "iterm2-nightly"
cask "karabiner-elements"
cask "keyboard-maestro"
cask "mailmate"
cask "marked"
cask "mplayerx"
cask "nvalt"
cask "sequel-pro"
cask "spotify"
cask "steam"
cask "trickster"
cask "virtualbox"
cask "visual-studio-code"
cask "xtrafinder"

#}}}
# Tools --------------------------------------------------------------------{{{

# Z Alternative
brew 'fasd'
# Quickly copy ssh keys
brew 'ssh-copy-id'
# Git deployment to servers without git
brew 'git-ftp'
# Donwload youtube videos
brew 'youtube-dl'
# CLI Fuzzy Finder
brew 'fzf'
# Tree folder architecture
brew 'tree'
# Better ack
brew 'the_silver_searcher'
# Faster newer version of 'Ag'
brew 'ripgrep'
# Pipe to vim
# echo 'text' | vipe
brew 'moreutils'
# Notifications
brew 'terminal-notifier'

#}}}
# Coding -------------------------------------------------------------------{{{

brew 'ctags'
brew 'editorconfig'

# JSON Parser
brew 'jq'

# HowDoI
# If the installation for howdoi fails execute this cmd:
# sudo chmod -R go+w /Library/Python/2.7/site-packages/
brew install https://raw.github.com/gleitz/howdoi/master/howdoi.rb

# Linters
brew 'CMake'
brew 'shellcheck'
brew 'phplint'

#}}}
# Coding -------------------------------------------------------------------{{{

mas "Moom", id: 419330170
mas "Xcode", id: 497799835

#}}}
