(spacemacs/set-leader-keys "gt" 'floscr-git/magit-stage-and-commit-current-buffer)
(spacemacs/set-leader-keys "gT" 'time-machine-transient-state)
(spacemacs/set-leader-keys "gc" 'magit-commit)
(spacemacs/set-leader-keys "gha" 'git-gutter:stage-hunk)
(spacemacs/set-leader-keys "ghn" 'git-gutter:next-hunk)
(spacemacs/set-leader-keys "ghp" 'git-gutter:previous-hunk)
(spacemacs/set-leader-keys "ghu" 'git-gutter:revert-hunk)

(define-key evil-normal-state-map (kbd "[c") 'git-gutter:previous-hunk)
(define-key evil-normal-state-map (kbd "]c") 'git-gutter:next-hunk)
